/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kolory;

/**
 *
 * @author paw-g
 */

import javax.swing.*;
import java.awt.*;
import java.util.Timer;
import java.util.TimerTask;
import java.util.Random;

import java.util.Timer;
import java.util.TimerTask;

public class Plansza extends javax.swing.JPanel {

    /**
     * Creates new form Boart
     */
    private Color[] kolory = { Color.GREEN, Color.BLUE, Color.RED, Color.MAGENTA, Color.CYAN, Color.YELLOW };
    int sekundy = 10;
    public Plansza() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        JButton buttons[] = new JButton[16];



        jPanelButtons = new javax.swing.JPanel();

        jPanelUpSet = new javax.swing.JPanel();
        jPanelWybranyKolor = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 0, 0));

        jPanelButtons.setBackground(new java.awt.Color(0, 0, 0));
        jPanelButtons.setLayout(new java.awt.GridLayout(4, 4));




        for(int i = 0; i<16; i++){

            buttons[i] = new JButton();
            buttons[i].setBackground(Color.GRAY);
            jPanelButtons.add(buttons[i]);

        }

        jPanelUpSet.setBackground(new java.awt.Color(102, 255, 102));



        int kutas = new Random().nextInt(6);        // losuje jebany kolor
        System.out.println("wylosowany = " + kutas);





        jPanelWybranyKolor.setBackground(kolory[kutas]);





        javax.swing.GroupLayout jPanelWybranyKolorLayout = new javax.swing.GroupLayout(jPanelWybranyKolor);
        jPanelWybranyKolor.setLayout(jPanelWybranyKolorLayout);
        jPanelWybranyKolorLayout.setHorizontalGroup(
                jPanelWybranyKolorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 562, Short.MAX_VALUE)
        );
        jPanelWybranyKolorLayout.setVerticalGroup(
                jPanelWybranyKolorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 224, Short.MAX_VALUE)
        );

        jTextField1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);





        jTextField1.setText("CZAS");
        liczczas();












        jTextField2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("PUNKTY,POZIOM");

        javax.swing.GroupLayout jPanelUpSetLayout = new javax.swing.GroupLayout(jPanelUpSet);
        jPanelUpSet.setLayout(jPanelUpSetLayout);
        jPanelUpSetLayout.setHorizontalGroup(
                jPanelUpSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1139, Short.MAX_VALUE)
                        .addGroup(jPanelUpSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUpSetLayout.createSequentialGroup()
                                        .addContainerGap(289, Short.MAX_VALUE)
                                        .addComponent(jPanelWybranyKolor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(288, Short.MAX_VALUE)))
                        .addGroup(jPanelUpSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUpSetLayout.createSequentialGroup()
                                        .addContainerGap(869, Short.MAX_VALUE)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(38, Short.MAX_VALUE)))
                        .addGroup(jPanelUpSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUpSetLayout.createSequentialGroup()
                                        .addContainerGap(39, Short.MAX_VALUE)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(872, Short.MAX_VALUE)))
        );
        jPanelUpSetLayout.setVerticalGroup(
                jPanelUpSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 236, Short.MAX_VALUE)
                        .addGroup(jPanelUpSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUpSetLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jPanelWybranyKolor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addContainerGap()))
                        .addGroup(jPanelUpSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUpSetLayout.createSequentialGroup()
                                        .addContainerGap(46, Short.MAX_VALUE)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(46, Short.MAX_VALUE)))
                        .addGroup(jPanelUpSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUpSetLayout.createSequentialGroup()
                                        .addContainerGap(50, Short.MAX_VALUE)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(44, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jPanelUpSet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, 1139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanelUpSet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
    }// </editor-fold>


    public int liczczas(){
        Timer timer = new Timer();
        TimerTask task = new TimerTask() {
            public void run(){
                sekundy--;
                jTextField1.setText(String.valueOf(sekundy));
            }
        };

        timer.scheduleAtFixedRate(task,1000,1000);
        return sekundy;
    }









    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JPanel jPanelUpSet;
    private javax.swing.JPanel jPanelWybranyKolor;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration
}
