/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kolory;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.Timer;
import java.util.TimerTask;
import java.util.Random;
import java.util.ArrayList;
import java.util.Collections;




public class Plansza extends javax.swing.JPanel {

    /**
     * Creates new form Boart
     */

    private Color[] kolory = {Color.GREEN, Color.BLUE, Color.RED, Color.MAGENTA, Color.CYAN, Color.YELLOW, Color.ORANGE};

    int liczba_punktow = 0;
    int wylosowany_przycisk = 2;
    boolean wybrano = false;
    int sekundy = 10;
    public static boolean koniec_rundy = false;
    int wybrany_kolor =0;
    int buf = 0;

    JButton buttons[] = new JButton[16];

    public Plansza() {
        initComponents();
        gra();





    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {


        jPanelButtons = new javax.swing.JPanel();

        jPanelUpSet = new javax.swing.JPanel();




        jPanelWybranyKolor = new javax.swing.JPanel();


        jTextField1 = new javax.swing.JTextField();
        jTextField1.setEnabled(false);
        jTextField1.setBackground(Color.darkGray);
        jTextField1.setForeground(Color.BLACK);


        jTextField2 = new javax.swing.JTextField();
        jTextField2.setBackground(Color.darkGray);
        jTextField2.setForeground(Color.BLACK);




        setBackground(new java.awt.Color(0, 0, 0));

        jPanelButtons.setBackground(new java.awt.Color(0, 0, 0));
        jPanelButtons.setLayout(new java.awt.GridLayout(4, 4));




        for(int i = 0; i<16; i++){

            buttons[i] = new JButton();
            buttons[i].setBackground(Color.darkGray);
            jPanelButtons.add(buttons[i]);
            buttons[i].addActionListener(this::actionPerformed);

        }

        jPanelUpSet.setBackground(Color.BLACK);



        javax.swing.GroupLayout jPanelWybranyKolorLayout = new javax.swing.GroupLayout(jPanelWybranyKolor);
        jPanelWybranyKolor.setLayout(jPanelWybranyKolorLayout);
        jPanelWybranyKolorLayout.setHorizontalGroup(
                jPanelWybranyKolorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 562, Short.MAX_VALUE)
        );
        jPanelWybranyKolorLayout.setVerticalGroup(
                jPanelWybranyKolorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 224, Short.MAX_VALUE)
        );

        jTextField1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);



        jTextField2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("PUNKTY,POZIOM");







        //--------------------------------------------------------------------------------------------------------------------------------
        javax.swing.GroupLayout jPanelUpSetLayout = new javax.swing.GroupLayout(jPanelUpSet);
        jPanelUpSet.setLayout(jPanelUpSetLayout);
        jPanelUpSetLayout.setHorizontalGroup(
                jPanelUpSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1139, Short.MAX_VALUE)
                        .addGroup(jPanelUpSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUpSetLayout.createSequentialGroup()
                                        .addContainerGap(289, Short.MAX_VALUE)
                                        .addComponent(jPanelWybranyKolor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(288, Short.MAX_VALUE)))
                        .addGroup(jPanelUpSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUpSetLayout.createSequentialGroup()
                                        .addContainerGap(869, Short.MAX_VALUE)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(38, Short.MAX_VALUE)))
                        .addGroup(jPanelUpSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUpSetLayout.createSequentialGroup()
                                        .addContainerGap(39, Short.MAX_VALUE)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(872, Short.MAX_VALUE)))
        );
        jPanelUpSetLayout.setVerticalGroup(
                jPanelUpSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 236, Short.MAX_VALUE)
                        .addGroup(jPanelUpSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUpSetLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jPanelWybranyKolor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addContainerGap()))
                        .addGroup(jPanelUpSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUpSetLayout.createSequentialGroup()
                                        .addContainerGap(46, Short.MAX_VALUE)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(46, Short.MAX_VALUE)))
                        .addGroup(jPanelUpSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUpSetLayout.createSequentialGroup()
                                        .addContainerGap(50, Short.MAX_VALUE)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(44, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jPanelUpSet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, 1139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanelUpSet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
    }// </editor-fold>
    //--------------------------------------------------------------------------------------------------------------------------------






    public int gra(){


        jTextField1.setText(String.valueOf(sekundy));
        Timer timer = new Timer();
        TimerTask task = new TimerTask() {



            public void run() {
                if (sekundy >= 0) {

                    sekundy--;
                    jTextField1.setText(String.valueOf(sekundy));
                    wybrany_kolor = new Random().nextInt(7);
                    if(wybrano == false) {

                        jPanelWybranyKolor.setBackground(kolory[wybrany_kolor]);
                        wybrano = true;
                        wylosowany_przycisk = losowanie_przycisku();
                        buttons[wylosowany_przycisk].setBackground(kolory[wybrany_kolor]);
                        inne_przyciski();


                    }



                } else {
                    jTextField1.setText("0");
                    koniec_rundy = true;
                    jTextField1.setText("Koniec GRY");
                }
            }
        };

        timer.scheduleAtFixedRate(task,1000,1000);
        return sekundy;
    }


    public void actionPerformed(java.awt.event.ActionEvent e) {
        Object source = e.getSource();
        if(source == buttons[wylosowany_przycisk] && sekundy> 0){
            liczba_punktow++;
            buttons[wylosowany_przycisk].setBackground(Color.darkGray);
            buttons[buf].setBackground(Color.darkGray);
            jTextField2.setText(String.valueOf(liczba_punktow));
            wybrano = false;


        }

    }


    public int losowanie_przycisku() {
        int los = 0;
        los = new Random().nextInt(16);
        System.out.println("wylosowany = " + los);
        return los;
    }

    public void inne_przyciski() {
       ArrayList<Color> kolory_dwa = new ArrayList<Color>();
        System.out.println(wybrany_kolor);
       for(int i = 0; i<7; i++){
           if(kolory[i] != kolory[wybrany_kolor]){
               kolory_dwa.add(kolory[i]);

           }
       }

       int ilosc =  0;
       ilosc =  new Random().nextInt(3);
       ilosc++;

       buf = wylosowany_przycisk;
       while(buf == wylosowany_przycisk){

           buf = new Random().nextInt(16);

       }

        buttons[buf].setBackground(kolory_dwa.get(2));

    }



    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JPanel jPanelUpSet;
    private javax.swing.JPanel jPanelWybranyKolor;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;

}
